[platformio]
default_envs = debug

[env]
platform     = espressif32
board        = esp32-s3-devkitc-1
framework    = arduino
lib_deps =
    knolleary/PubSubClient @ ^2.8.0
    bblanchon/ArduinoJson  @ ^7.0.0
    miguelbalboa/MFRC522   @ ^1.4.10
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize
build_flags =
    -DCORE_DEBUG_LEVEL=0
    !python3 scripts/inject_env.py

[env:debug]
build_type  = debug
build_flags = ${env.build_flags} -DDEBUG_MODE=1 -DCORE_DEBUG_LEVEL=3
upload_speed = 921600

[env:release]
build_type  = release
build_flags = ${env.build_flags} -DDEBUG_MODE=0 -Os
upload_speed = 921600

[env:ota]
extends         = env:release
upload_protocol = espota
upload_port     = ${sysenv.ESP32_IP}
